
CREATE SEQUENCE user_seq START WITH 1000 INCREMENT BY 1;


CREATE SEQUENCE chat_seq START WITH 1000 INCREMENT BY 1;


CREATE SEQUENCE message_seq START WITH 10000 INCREMENT BY 1;


CREATE SEQUENCE file_seq START WITH 1000 INCREMENT BY 1;


CREATE SEQUENCE feedback_seq START WITH 1000 INCREMENT BY 1;

CREATE SEQUENCE audit_seq START WITH 1000 INCREMENT BY 1;